"use client";

import { Download, Filter, Printer, Search, ShieldCheck, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AssetRecord } from "../lib/demo-data";
import { exportReport, type ReportFormat } from "../lib/report-export";

type WorkOrder={id:string;assetId:string;assetName:string;title:string;description:string;status:string;priority:string;assignee:string;dueDate:string;startedAt?:string;completedAt?:string;createdAt:string;resolution?:string};
type MaintenanceTask={id:string;title:string;cadence:string;nextDue:string;status:string;source:string;workOrderId?:string};
type ServiceEvent={id:string;type:string;title:string;performedBy:string;performedAt:string;notes:string};
type Bundle={asset:AssetRecord;tasks?:MaintenanceTask[];orders?:WorkOrder[];events?:ServiceEvent[]};
type HistoryRow={date:string;type:string;reference:string;status:string;technician:string;details:string};
const today=()=>new Date().toISOString().slice(0,10);
function workState(order:WorkOrder){if(order.status==="Completed")return"Completed";if(order.startedAt||order.status.toLowerCase()==="in progress")return"In progress";if(order.dueDate&&order.dueDate<today())return"Overdue";return"Scheduled"}

export default function ReportsPage(){
 const[assets,setAssets]=useState<AssetRecord[]>([]),[orders,setOrders]=useState<WorkOrder[]>([]),[selected,setSelected]=useState(""),[bundle,setBundle]=useState<Bundle|null>(null),[format,setFormat]=useState<ReportFormat>("pdf"),[query,setQuery]=useState(""),[project,setProject]=useState("all"),[status,setStatus]=useState("all"),[workStatus,setWorkStatus]=useState("all"),[location,setLocation]=useState("all");
 useEffect(()=>{Promise.all([fetch("/api/assets",{cache:"no-store"}),fetch("/api/work-orders",{cache:"no-store"})]).then(async([a,w])=>{const ad=await a.json(),wd=await w.json();setAssets(ad.assets||[]);setOrders(wd.workOrders||[])}).catch(()=>{})},[]);
 const projects=useMemo(()=>Array.from(new Set(assets.map(a=>a.project))).sort(),[assets]),locations=useMemo(()=>Array.from(new Set(assets.map(a=>a.location))).sort(),[assets]),statuses=useMemo(()=>Array.from(new Set(assets.map(a=>a.status))).sort(),[assets]);
 const matching=useMemo(()=>assets.filter(a=>{const text=`${a.name} ${a.id} ${a.model} ${a.serialNumber}`.toLowerCase();const ownOrders=orders.filter(o=>o.assetId===a.id);return(!query||text.includes(query.toLowerCase()))&&(project==="all"||a.project===project)&&(status==="all"||a.status===status)&&(location==="all"||a.location===location)&&(workStatus==="all"||ownOrders.some(o=>workState(o)===workStatus))}),[assets,orders,query,project,status,location,workStatus]);
 useEffect(()=>{if(!matching.some(a=>a.id===selected))setSelected(matching[0]?.id||"")},[matching,selected]);
 useEffect(()=>{if(!selected){setBundle(null);return}fetch(`/api/assets/${encodeURIComponent(selected)}`,{cache:"no-store"}).then(r=>r.json()).then(setBundle).catch(()=>setBundle(null))},[selected]);
 const asset=matching.find(a=>a.id===selected)||bundle?.asset;
 const history=useMemo<HistoryRow[]>(()=>{if(!bundle)return[];const rows:HistoryRow[]=[];for(const t of bundle.tasks||[])rows.push({date:t.nextDue||"",type:"Maintenance task",reference:t.workOrderId||t.id,status:t.status||"Planned",technician:"",details:`${t.title}${t.cadence?` · ${t.cadence}`:""}${t.source?` · ${t.source}`:""}`});for(const o of bundle.orders||[])rows.push({date:o.completedAt||o.startedAt||o.createdAt||o.dueDate,type:"Work order",reference:o.id,status:workState(o),technician:o.assignee||"",details:`${o.title}${o.resolution?` · Resolution: ${o.resolution}`:o.description?` · ${o.description}`:""}`});for(const e of bundle.events||[])rows.push({date:e.performedAt||"",type:e.type||"Service event",reference:e.id,status:"Recorded",technician:e.performedBy||"",details:`${e.title}${e.notes?` · ${e.notes}`:""}`});return rows.sort((a,b)=>new Date(b.date||0).getTime()-new Date(a.date||0).getTime())},[bundle]);
 async function download(){if(!asset)return;await exportReport({title:`SmartCare Maintenance History — ${asset.name}`,format,columns:[{key:"date",label:"Date"},{key:"type",label:"History type"},{key:"reference",label:"Reference"},{key:"status",label:"Status"},{key:"technician",label:"Technician"},{key:"details",label:"Maintenance / repair details"}],rows:history as unknown as Record<string,unknown>[],meta:{project:asset.project,details:{"Asset ID":asset.id,"Equipment":asset.name,"Model":asset.model||"Not recorded","Serial":asset.serialNumber||"Not recorded","Location":asset.location,"Asset status":asset.status,"Health":`${asset.health}%`},filters:{Project:project,Status:status,"Work order":workStatus,Location:location,Search:query||"None"}}})}
 const openOrders=(bundle?.orders||[]).filter(o=>!["Completed","Cancelled"].includes(o.status)).length;
 return <main className="dashboard-main section-page report-page"><section className="page-heading no-print"><div><p className="eyebrow">Maintenance & asset history</p><h1>Asset Reports</h1><p className="page-subtitle">Filter equipment by project, condition, work-order state and location, then export its complete maintenance history without financial values.</p></div><div className="heading-actions"><label>Format<select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={()=>window.print()}><Printer size={18}/> Print</button><button className="button primary" onClick={download} disabled={!asset}><Download size={18}/> Export history</button></div></section>
 <section className="toolbar-card no-print"><label className="page-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search machine, Asset ID, model or serial"/></label><label className="filter-select"><Filter size={16}/>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{projects.map(v=><option key={v}>{v}</option>)}</select></label><label className="filter-select">Asset status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label className="filter-select">Work order<select value={workStatus} onChange={e=>setWorkStatus(e.target.value)}><option value="all">All work orders</option><option>Scheduled</option><option>In progress</option><option>Overdue</option></select></label><label className="filter-select">Location<select value={location} onChange={e=>setLocation(e.target.value)}><option value="all">All locations</option>{locations.map(v=><option key={v}>{v}</option>)}</select></label></section>
 <section className="report-controls no-print"><label>Equipment<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select equipment</option>{matching.map(a=><option value={a.id} key={a.id}>{a.name} · {a.id}</option>)}</select></label><span className="result-count">{matching.length} matching assets</span></section>
 {asset?<article className="report-sheet"><header className="report-header"><div className="report-logo image"><img src="/ibtechar-main-logo.png" alt="Ibtechar" width={190} height={80}/></div><div><span>MAINTENANCE HISTORY REPORT</span><strong>{asset.id}</strong><small>{new Date().toLocaleString()}</small></div></header><section className="equipment-report-hero"><div className={`equipment-photo ${asset.tone}`}>{asset.imageData?<img src={asset.imageData} alt={asset.name}/>:<Wrench size={52}/>}</div><div><p>{asset.project} · {asset.category}</p><h1>{asset.name}</h1><span>{asset.manufacturer} · {asset.model}</span><strong className={`table-status ${asset.tone}`}>{asset.status}</strong></div></section><section className="report-metrics"><article><strong>{asset.health}%</strong><span>Health score</span></article><article><strong>{asset.location}</strong><span>Location</span></article><article><strong>{openOrders}</strong><span>Open work orders</span></article><article><strong>{history.length}</strong><span>History records</span></article></section><section className="report-section"><h2>Asset passport</h2><table className="report-table"><tbody><tr><th>Project</th><td>{asset.project}</td><th>Location</th><td>{asset.location}</td></tr><tr><th>Serial</th><td>{asset.serialNumber||"Not recorded"}</td><th>Warranty until</th><td>{asset.warrantyUntil||"Not recorded"}</td></tr><tr><th>Status</th><td>{asset.status}</td><th>Description</th><td>{asset.notes||"No description recorded"}</td></tr></tbody></table></section><section className="report-section"><h2>Complete maintenance history</h2><div className="responsive-table"><table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Status</th><th>Technician</th><th>Details</th></tr></thead><tbody>{history.map((r,i)=><tr key={`${r.reference}-${i}`}><td>{r.date?new Date(r.date).toLocaleString():"—"}</td><td>{r.type}</td><td>{r.reference}</td><td>{r.status}</td><td>{r.technician||"—"}</td><td>{r.details}</td></tr>)}{!history.length&&<tr><td colSpan={6} className="empty-row">No maintenance history recorded for this asset.</td></tr>}</tbody></table></div></section><section className="safety-result"><ShieldCheck/><div><h3>Operational report</h3><p>This report intentionally excludes purchase cost, depreciation and current-value information.</p></div></section></article>:<section className="empty-state"><h2>No matching equipment</h2><p>Change the filters or search terms to select an asset.</p></section>}
 </main>
}
