"use client";

import { Download, Printer, ShieldCheck, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { depreciationFor, type AssetRecord } from "../lib/demo-data";
import { exportReport, type ReportFormat } from "../lib/report-export";

const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});

export default function ReportsPage(){
  const[assets,setAssets]=useState<AssetRecord[]>([]),[selected,setSelected]=useState(""),[format,setFormat]=useState<ReportFormat>("pdf");
  useEffect(()=>{fetch("/api/assets",{cache:"no-store"}).then(response=>response.json()).then((data:{assets?:AssetRecord[]})=>{const rows=data.assets||[];setAssets(rows);setSelected(current=>current||rows[0]?.id||"")}).catch(()=>setAssets([]))},[]);
  const asset=assets.find(item=>item.id===selected);
  const currentValue=asset?depreciationFor(asset).netBookValue:0;
  const portfolio=useMemo(()=>assets.reduce((sum,item)=>sum+depreciationFor(item).netBookValue,0),[assets]);
  async function download(){await exportReport({title:"SmartCare Asset Management Report",format,columns:[{key:"id",label:"Asset ID"},{key:"name",label:"Equipment"},{key:"project",label:"Project"},{key:"location",label:"Location"},{key:"status",label:"Status"},{key:"cost",label:"Purchase QAR"},{key:"value",label:"Current QAR"},{key:"warranty",label:"Warranty until"},{key:"insured",label:"Insured"}],rows:assets.map(item=>({id:item.id,name:item.name,project:item.project,location:item.location,status:item.status,cost:item.acquisitionCost,value:Math.round(depreciationFor(item).netBookValue),warranty:item.warrantyUntil,insured:item.insured?"Yes":"No"})),meta:{details:{"Generated at":new Date().toLocaleString(),"Portfolio current value":money.format(portfolio)}}})}
  return <main className="dashboard-main section-page report-page"><section className="page-heading no-print"><div><p className="eyebrow">Operational & executive intelligence</p><h1>Asset Reports</h1><p className="page-subtitle">Live reports generated from the assets visible to your Supabase account.</p></div><div className="heading-actions"><label>Format<select value={format} onChange={event=>setFormat(event.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={()=>window.print()}><Printer size={18}/> Print</button><button className="button primary" onClick={download}><Download size={18}/> Export</button></div></section>
  <section className="report-controls no-print"><label>Equipment<select value={selected} onChange={event=>setSelected(event.target.value)}>{assets.map(item=><option value={item.id} key={item.id}>{item.name} · {item.id}</option>)}</select></label></section>
  {asset?<article className="report-sheet"><header className="report-header"><div className="report-logo image"><img src="/ibtechar-main-logo.png" alt="Ibtechar" width={190} height={80}/></div><div><span>EQUIPMENT CONDITION REPORT</span><strong>{asset.id}</strong><small>{new Date().toLocaleString()}</small></div></header><section className="equipment-report-hero"><div className={`equipment-photo ${asset.tone}`}>{asset.imageData?<img src={asset.imageData} alt={asset.name}/>:<Wrench size={52}/>}</div><div><p>{asset.category}</p><h1>{asset.name}</h1><span>{asset.manufacturer} · {asset.model}</span><strong className={`table-status ${asset.tone}`}>{asset.status}</strong></div></section><section className="report-metrics"><article><strong>{asset.health}%</strong><span>Health score</span></article><article><strong>{money.format(asset.acquisitionCost)}</strong><span>Purchase value</span></article><article><strong>{money.format(currentValue)}</strong><span>Current book value</span></article><article><strong>{asset.warrantyUntil&&asset.warrantyUntil>=new Date().toISOString().slice(0,10)?"Active":"Expired"}</strong><span>Warranty</span></article></section><section className="report-section"><h2>Asset passport</h2><table className="report-table"><tbody><tr><th>Project</th><td>{asset.project}</td><th>Location</th><td>{asset.location}</td></tr><tr><th>Serial</th><td>{asset.serialNumber}</td><th>Last used/check</th><td>{asset.lastSeen||"Not recorded"}</td></tr><tr><th>Open box</th><td>{asset.openBox?"Yes":"No"}</td><th>Insured</th><td>{asset.insured?"Yes":"No"}</td></tr><tr><th>Damage adjustment</th><td>{asset.damagePercent||0}%</td><th>Warnings</th><td>{asset.warningCount||0}</td></tr></tbody></table></section><section className="safety-result"><ShieldCheck/><div><h3>Valuation note</h3><p>Current value uses straight-line depreciation with the stored residual value, useful life and purchase date. Condition fields remain visible for management review.</p></div></section></article>:<section className="empty-state"><h2>No accessible assets</h2><p>Add an asset or request project permission from an administrator.</p></section>}
  </main>;
}

