"use client";
import { CheckCircle2,Edit3,FileDown,FilePlus2,Printer,ShoppingCart,Trash2,X } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { exportReport,type ReportFormat } from "../lib/report-export";
import { useSmartCareAuth } from "../components/auth-provider";
type PO={id:string;date:string;supplier:string;equipment:string;equipmentType:"Asset"|"Consumable";budgetBranch:string;project:string;location:string;quantity:number;unitPrice:number;total:number;status:string;assetCreated:boolean};
type Project={id:string;name:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:2});
const statuses=["Rejected","Approved","Review","Draft","Received damaged","Delivered","Shipped","Received","Other"];
export default function ProcurementPage(){
 const{user}=useSmartCareAuth();
 const[orders,setOrders]=useState<PO[]>([]),[projects,setProjects]=useState<Project[]>([]),[created,setCreated]=useState<PO|null>(null),[editing,setEditing]=useState<PO|null>(null),[status,setStatus]=useState("all"),[project,setProject]=useState("all"),[supplier,setSupplier]=useState("all"),[format,setFormat]=useState<ReportFormat>("pdf"),[error,setError]=useState("");
 async function refresh(){const[o,p]=await Promise.all([fetch("/api/purchase-orders",{cache:"no-store"}),fetch("/api/projects",{cache:"no-store"})]),[od,pd]=await Promise.all([o.json(),p.json()]);setOrders(od.orders||[]);setProjects(pd.projects||[])}useEffect(()=>{refresh().catch(()=>setError("Unable to load procurement data."))},[]);
 const suppliers=useMemo(()=>Array.from(new Set(orders.map(o=>o.supplier))).sort(),[orders]),rows=useMemo(()=>orders.filter(o=>(status==="all"||o.status===status)&&(project==="all"||o.project===project)&&(supplier==="all"||o.supplier===supplier)),[orders,status,project,supplier]);
 async function issue(fd:FormData){const equipmentType=String(fd.get("equipmentType"));const payload={supplier:String(fd.get("supplier")),equipment:String(fd.get("equipment")),equipmentType,project:String(fd.get("project")),location:String(fd.get("location")),quantity:Number(fd.get("quantity")),unitPrice:Number(fd.get("unitPrice")),budgetBranch:equipmentType==="Asset"?"Equipment":"Consumables",requester:user?.name||"SmartCare user"};const r=await fetch("/api/purchase-orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setError(d.error||"Unable to create PO");return}setCreated(d.order);await refresh()}
 async function update(fd:FormData){if(!editing)return;const payload={date:String(fd.get("date")),supplier:String(fd.get("supplier")),equipment:String(fd.get("equipment")),equipmentType:String(fd.get("equipmentType")),budgetBranch:String(fd.get("budgetBranch")),project:String(fd.get("project")),location:String(fd.get("location")),quantity:Number(fd.get("quantity")),unitPrice:Number(fd.get("unitPrice")),status:String(fd.get("status"))};const r=await fetch(`/api/purchase-orders/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok){const d=await r.json();setCreated(d.order);setEditing(null);await refresh()}else setError("Unable to update PO")}
 async function remove(id:string){if(!window.confirm(`Delete purchase order ${id}?`))return;const r=await fetch(`/api/purchase-orders/${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok){if(created?.id===id)setCreated(null);await refresh()}else setError("Unable to delete PO")}
 async function report(){await exportReport({title:"Procurement & Purchase Order Report",format,columns:[{key:"id",label:"PO"},{key:"date",label:"Date"},{key:"supplier",label:"Supplier"},{key:"equipment",label:"Equipment"},{key:"project",label:"Project"},{key:"total",label:"Value QAR"},{key:"status",label:"Status"}],rows:rows as unknown as Record<string,unknown>[],meta:{filters:{Status:status,Project:project,Supplier:supplier}}})}
 return <main className="dashboard-main section-page procurement-page"><section className="page-heading no-print"><div><p className="eyebrow">Purchase-to-asset control</p><h1>Procurement & Purchase Orders</h1><p className="page-subtitle">Create, edit, update and delete purchase orders with budget recalculation.</p></div><span className="pilot-badge"><ShoppingCart size={16}/> Database linked</span></section>{error&&<p className="form-error">{error}</p>}
 <section className="procurement-layout"><article className="diagnostic-form-card no-print"><div className="assistant-header"><span><FilePlus2/></span><div><h2>Issue purchase order</h2><p>Issuing creates a PO in the register and an approval item in Purchase Requests. New POs start in Review.</p></div></div><form action={issue}><label>Supplier<input name="supplier" required/></label><label>Equipment description<input name="equipment" required/></label><label>Equipment type<select name="equipmentType" defaultValue="Asset"><option>Asset</option><option>Consumable</option></select><small className="field-note">Asset → Equipment budget; Consumable → Consumables budget.</small></label><div className="form-grid"><label>Project<select name="project">{projects.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Delivery location<select name="location"><option>STUDIO 5</option><option>IBTECHAR_OFFICE</option><option>IBTECHAR_STORE</option><option>MCIT</option><option>TEEN_HUT</option></select></label></div><div className="form-grid"><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Unit price (QAR)<input name="unitPrice" type="number" min="0" step="0.01" required/></label></div><button className="button primary full"><FilePlus2 size={18}/> Issue purchase order</button></form></article>
 <article className="po-sheet"><header><img src="/ibtechar-main-logo.png" alt="Ibtechar" width={190} height={86}/><div><span>PURCHASE ORDER</span><strong>{created?.id||"IBT-PO-DRAFT"}</strong><small>{created?.date||new Date().toISOString().slice(0,10)}</small></div></header>{created?<><section><p>Supplier</p><h2>{created.supplier}</h2><span>Project: {created.project} · Deliver to: {created.location}</span></section><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody><tr><td>{created.equipment}</td><td>{created.quantity}</td><td>{money.format(created.unitPrice)}</td><td><strong>{money.format(created.total)}</strong></td></tr></tbody></table><div className="po-total"><span>Total</span><strong>{money.format(created.total)}</strong></div><p className="po-status"><CheckCircle2/> {created.status}</p><button className="button secondary no-print" onClick={()=>window.print()}><Printer size={18}/> Print / Save PDF</button></>:<div className="po-empty"><ShoppingCart size={38}/><h2>PO preview</h2><p>Create or open a purchase order.</p></div>}</article></section>
 <section className="toolbar-card no-print"><label className="filter-select">Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="filter-select">Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{projects.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label className="filter-select">Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="all">All suppliers</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></label><label className="filter-select">Report<select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={report}><FileDown size={16}/> Generate report</button></section>
 <section className="budget-table-card no-print"><div className="panel-heading"><h2>Purchase order register</h2><span>{rows.length} records</span></div><div className="responsive-table"><table><thead><tr><th>PO</th><th>Equipment</th><th>Type</th><th>Supplier</th><th>Project / Branch</th><th>Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><button className="text-button" onClick={()=>setCreated(o)}>{o.id}</button><small>{o.date}</small></td><td>{o.equipment}</td><td>{o.equipmentType}</td><td>{o.supplier}</td><td>{o.project}<small>{o.budgetBranch}</small></td><td>{money.format(o.total)}</td><td>{o.status}{o.assetCreated&&<small>Asset registered</small>}</td><td><div className="table-actions"><button onClick={()=>setEditing(o)}><Edit3 size={15}/> Edit</button><button className="danger" onClick={()=>remove(o.id)}><Trash2 size={15}/> Delete</button></div></td></tr>)}</tbody></table></div></section>
 {editing&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setEditing(null)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">{editing.id}</p><h2>Edit purchase order</h2></div><button className="modal-close inline" onClick={()=>setEditing(null)}><X/></button></div><form action={update}><label>Date<input name="date" type="date" defaultValue={editing.date}/></label><label>Supplier<input name="supplier" defaultValue={editing.supplier} required/></label><label>Equipment<input name="equipment" defaultValue={editing.equipment} required/></label><div className="form-grid"><label>Equipment type<select name="equipmentType" defaultValue={editing.equipmentType}><option>Asset</option><option>Consumable</option></select></label><label>Budget branch<select name="budgetBranch" defaultValue={editing.budgetBranch}><option>Equipment</option><option>Consumables</option><option>Marketing</option><option>Call-off</option></select></label></div><div className="form-grid"><label>Project<select name="project" defaultValue={editing.project}>{projects.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Location<input name="location" defaultValue={editing.location}/></label></div><div className="form-grid"><label>Quantity<input name="quantity" type="number" min="1" defaultValue={editing.quantity}/></label><label>Unit price<input name="unitPrice" type="number" min="0" step=".01" defaultValue={editing.unitPrice}/></label></div><label>Status<select name="status" defaultValue={editing.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="button primary full">Update purchase order</button></form></section></div>}</main>
}
