"use client";
import { Bell,CheckCircle2,FileDown,Mail,Send,ShieldCheck,ShoppingCart,XCircle } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { useSmartCareAuth } from "../components/auth-provider";
type Project={id:string;name:string;approvedBudget:number;committed:number;spent:number};
type PR={id:string;date:string;project:string;fundingProject:string;reason:string;budgetBranch:string;amount:number;description:string;requester:string;status:string;purchaseOrderId?:string};
type Notice={id:number;entityId:string;title:string;message:string;createdAt:string;userName?:string;email?:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:2}),branches=["Marketing","Equipment","Consumables","Call-off"];
export default function PurchaseRequestsPage(){
 const{user,can}=useSmartCareAuth();
 const[projects,setProjects]=useState<Project[]>([]),[requests,setRequests]=useState<PR[]>([]),[funding,setFunding]=useState(""),[selected,setSelected]=useState<PR|null>(null),[notifications,setNotifications]=useState<Notice[]>([]),[error,setError]=useState("");
 async function refresh(){const[p,r]=await Promise.all([fetch("/api/projects",{cache:"no-store"}),fetch("/api/purchase-requests",{cache:"no-store"})]),[pd,rd]=await Promise.all([p.json(),r.json()]);setProjects(pd.projects||[]);setRequests(rd.requests||[]);if(!funding&&pd.projects?.length)setFunding(pd.projects[0].name)}
 useEffect(()=>{refresh().catch(()=>setError("Unable to load purchase requests."))},[]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("open");if(requested){const item=requests.find(r=>r.id===requested);if(item)setSelected(item)}},[requests]);
 useEffect(()=>{if(!selected){setNotifications([]);return}fetch(`/api/notifications?entityId=${encodeURIComponent(selected.id)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>setNotifications(d.notifications||[])).catch(()=>{})},[selected]);
 const names=useMemo(()=>projects.map(p=>p.name),[projects]),budget=projects.find(p=>p.name===funding);
 async function submit(fd:FormData){const payload={project:String(fd.get("project")),fundingProject:String(fd.get("funding")),reason:String(fd.get("reason")),budgetBranch:String(fd.get("branch")),amount:Number(fd.get("amount")),description:String(fd.get("description")),requester:user?.name||"SmartCare user",status:"Submitted"};const r=await fetch("/api/purchase-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setError(d.error||"Unable to submit request");return}setSelected(d.request);await refresh()}
 async function setDecision(decision:"approved"|"rejected"){if(!selected||!["CEO","ADMIN","FINANCE"].includes(user?.role||""))return;const r=await fetch(`/api/purchase-requests/${encodeURIComponent(selected.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({decision})}),d=await r.json();if(r.ok){setSelected(d.request);await refresh();const n=await fetch(`/api/notifications?entityId=${encodeURIComponent(selected.id)}`).then(x=>x.json());setNotifications(n.notifications||[])}else setError(d.error||"Unable to record decision")}
 function prepareEmail(){if(!selected)return;const subject=encodeURIComponent(`Approval required | ${selected.id} | ${money.format(selected.amount)}`),body=encodeURIComponent(`Purchasing Request: ${selected.id}\nProject: ${selected.project}\nFunding: ${selected.fundingProject} · ${selected.budgetBranch}\nValue: ${money.format(selected.amount)}\n\n${selected.description}`);window.location.href=`mailto:saif@ibtechar.com,omar@ibtechar.com?subject=${subject}&body=${body}`}
 return <main className="dashboard-main section-page purchase-request-page"><section className="page-heading no-print"><div><p className="eyebrow">Approval workflow</p><h1>Purchasing Requests</h1><p className="page-subtitle">An approved request creates a Review purchase order for Procurement. Only CEO, Admin, or Finance may approve or reject.</p></div><span className="pilot-badge"><ShieldCheck size={16}/> Controlled approval</span></section>{error&&<p className="form-error">{error}</p>}
 <section className="request-layout"><article className="diagnostic-form-card no-print"><div className="assistant-header"><span><Send/></span><div><h2>New purchasing request</h2><p>Every submission creates notifications for the requester and authorized approvers.</p></div></div><form action={submit}><div className="form-grid"><label>Request project<select name="project">{names.map(n=><option key={n}>{n}</option>)}</select></label><label>Funding budget<select name="funding" value={funding} onChange={e=>setFunding(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></label></div><label>Budget branch<select name="branch">{branches.map(n=><option key={n}>{n}</option>)}</select><small className="field-note">Available: {money.format((budget?.approvedBudget||0)-(budget?.committed||0)-(budget?.spent||0))}</small></label><label>Reason<select name="reason"><option>New equipment / asset</option><option>Replacement or repair</option><option>Marketing requirement</option><option>Consumables replenishment</option><option>Call-off service</option></select></label><div className="form-grid"><label>Request value (QAR)<input name="amount" type="number" min="1" step="0.01" required/></label><label>Requested by<input value={user?.name||"SmartCare user"} readOnly/></label></div><label>Business justification<textarea name="description" required rows={4}/></label><button className="button primary full"><Send size={18}/> Submit request</button></form></article>
 <article className="request-sheet"><header><img src="/ibtechar-main-logo.png" alt="Ibtechar" width={190} height={86}/><div><span>PURCHASING REQUEST</span><strong>{selected?.id||"IBT-PR-DRAFT"}</strong><small>{selected?.date||new Date().toISOString().slice(0,10)}</small></div></header>{selected?<><section className="request-summary"><div><small>Project</small><strong>{selected.project}</strong></div><div><small>Funding budget</small><strong>{selected.fundingProject}</strong></div><div><small>Budget branch</small><strong>{selected.budgetBranch}</strong></div><div><small>Source</small><strong>{selected.purchaseOrderId?`PO ${selected.purchaseOrderId}`:"Direct request"}</strong></div></section><section className="request-description"><small>Business justification</small><p>{selected.description}</p><span>Requested by <strong>{selected.requester}</strong></span></section><div className="request-total"><span>Requested value</span><strong>{money.format(selected.amount)}</strong></div><div className={`approval-state ${selected.status.toLowerCase().includes("approved")?"approved":selected.status.toLowerCase().includes("rejected")?"rejected":"pending"}`}><CheckCircle2/><span><strong>{selected.status}</strong><small>{selected.status==="Submitted"?"Waiting for CEO, Admin, or Finance.":selected.purchaseOrderId?`PO ${selected.purchaseOrderId} is ready in Procurement for editing and final decision.`:"Decision recorded and parties notified."}</small></span></div><div className="request-actions no-print"><button className="button secondary" onClick={()=>window.print()}><FileDown size={17}/> Print / Save PDF</button><button className="button secondary" onClick={prepareEmail}><Mail size={17}/> Prepare email</button>{selected.purchaseOrderId&&<a className="button secondary" href={`/procurement?open=${encodeURIComponent(selected.purchaseOrderId)}`}><ShoppingCart size={17}/> Open PO register</a>}</div>{["CEO","ADMIN","FINANCE"].includes(user?.role||"")&&selected.status==="Submitted"&&<div className="omar-actions no-print"><span>Authorized decision · {user?.name}</span><button className="approve" onClick={()=>setDecision("approved")}><CheckCircle2 size={16}/> Approve & create PO</button><button className="reject" onClick={()=>setDecision("rejected")}><XCircle size={16}/> Reject</button></div>}</>:<div className="po-empty"><Send size={38}/><h2>Approval sheet preview</h2><p>Select or submit a request.</p></div>}</article></section>
 {selected&&<section className="budget-table-card no-print"><div className="panel-heading"><div><h2><Bell size={17}/> Notification activity</h2><p>Recipients created automatically for this request.</p></div></div><div className="notification-list">{notifications.map(n=><div key={n.id}><Bell size={15}/><span><strong>{n.userName||n.email||"SmartCare user"} · {n.title}</strong><small>{n.message} · {new Date(n.createdAt).toLocaleString()}</small></span></div>)}{!notifications.length&&<p className="empty-row">No notification records yet.</p>}</div></section>}
 <section className="budget-table-card no-print"><div className="panel-heading"><h2>Request register</h2></div><div className="responsive-table"><table><thead><tr><th>Request</th><th>Source</th><th>Project</th><th>Budget branch</th><th>Value</th><th>Status</th><th/></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.date} · {r.reason}</small></td><td>{r.purchaseOrderId||"Direct"}</td><td>{r.project}<small>Funded by {r.fundingProject}</small></td><td>{r.budgetBranch}</td><td>{money.format(r.amount)}</td><td>{r.status}</td><td><button className="text-button" onClick={()=>setSelected(r)}>Open</button></td></tr>)}</tbody></table></div></section></main>
}
