"use client";
import { ArrowLeft, BrainCircuit, CheckCircle2, ClipboardList, MapPin, PackageCheck, Pencil, ReceiptText, ShieldCheck, Wrench } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Asset={id:string;name:string;manufacturer:string;model:string;serialNumber:string;category:string;location:string;project:string;status:string;tone:string;health:number;acquisitionCost:number;residualValue:number;usefulLifeYears:number;purchaseDate:string;warrantyUntil:string;insured:boolean;openBox:boolean;damagePercent:number;purchaseOrderId?:string;notes?:string};
const toneForStatus=(status:string)=>status==="Operational"?"healthy":status==="Out of service"?"warning":"due";
type PurchaseOrder={id:string;po_date:string;supplier:string;equipment:string;total:number;status:string;received_at?:string;received_condition?:string;received_manufacturer?:string;received_model?:string;received_serial_number?:string;received_warranty_until?:string};
type Diagnostic={id:number;symptom:string;result?:{title?:string;recommendedAction?:string};createdAt:string};
type WorkOrder={id:string;title:string;status:string;createdAt:string;startedAt?:string;completedAt?:string;resolution?:string;assignee?:string};
type ServiceEvent={id:string;type:string;title:string;performedBy:string;performedAt:string;notes:string};
type Bundle={asset:Asset;purchaseOrder?:PurchaseOrder|null;diagnostics?:Diagnostic[];orders?:WorkOrder[];events?:ServiceEvent[]};
type TimelineItem={key:string;date:string;title:string;description:string;kind:"purchase"|"receive"|"asset"|"ai"|"wo"|"repair"|"complete"};
const iconFor=(kind:TimelineItem["kind"])=>kind==="purchase"?ReceiptText:kind==="receive"?PackageCheck:kind==="ai"?BrainCircuit:kind==="wo"?ClipboardList:kind==="complete"?CheckCircle2:Wrench;
export default function AssetDetailPage({params}:{params:Promise<{id:string}>}){
 const[bundle,setBundle]=useState<Bundle|null>(null),[locations,setLocations]=useState<{name:string}[]>([]),[editing,setEditing]=useState(false),[error,setError]=useState("");
 async function refresh(){const{id}=await params;const[a,l]=await Promise.all([fetch(`/api/assets/${id}`,{cache:"no-store"}).then(r=>r.json()),fetch("/api/locations").then(r=>r.json())]);setBundle(a);setLocations(l.locations||[])}
 useEffect(()=>{refresh().catch(()=>setError("Unable to load asset."))},[params]);
 const asset=bundle?.asset;
 const timeline=useMemo(()=>{if(!bundle?.asset)return[];const rows:TimelineItem[]=[];const po=bundle.purchaseOrder;if(po){rows.push({key:`po-${po.id}`,date:po.po_date,title:`Purchase Order ${po.id}`,description:`${po.equipment} ordered from ${po.supplier} · QAR ${Number(po.total||0).toLocaleString()}.`,kind:"purchase"});if(po.received_at)rows.push({key:`recv-${po.id}`,date:po.received_at,title:"Equipment Received",description:`${po.received_condition||"Received"} · ${bundle.asset.location}${po.received_warranty_until?` · Warranty to ${po.received_warranty_until}`:""}.`,kind:"receive"});}
 for(const e of bundle.events||[])rows.push({key:e.id,date:e.performedAt,title:e.title,description:e.notes||e.performedBy||"Lifecycle event",kind:e.type==="Repair Started"?"repair":e.type==="Repair Completed"?"complete":"asset"});
 for(const d of bundle.diagnostics||[])rows.push({key:`diag-${d.id}`,date:d.createdAt,title:`AI Diagnostic #${d.id}`,description:`${d.symptom}${d.result?.recommendedAction?` · ${d.result.recommendedAction}`:""}`,kind:"ai"});
 for(const w of bundle.orders||[]){rows.push({key:`wo-${w.id}`,date:w.createdAt,title:`Work Order ${w.id} Created`,description:`${w.title} · ${w.status}.`,kind:"wo"});}
 return rows.sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime())},[bundle]);
 async function save(fd:FormData){if(!asset)return;const nextStatus=String(fd.get("status"));const payload={...asset,location:String(fd.get("location")),status:nextStatus,tone:toneForStatus(nextStatus),health:Number(fd.get("health")),warrantyUntil:String(fd.get("warrantyUntil")),insured:fd.get("insured")==="on",notes:String(fd.get("notes")||"")};const r=await fetch(`/api/assets/${asset.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(r.ok){setEditing(false);await refresh()}else setError(d.error||"Unable to update asset.")}
 if(!asset)return <main className="dashboard-main section-page">Loading asset…</main>;
 const age=Math.max(0,(Date.now()-new Date(asset.purchaseDate||Date.now()).getTime())/(365.25*86400000));const current=Math.max(asset.residualValue,asset.acquisitionCost-(asset.acquisitionCost-asset.residualValue)*Math.min(1,age/Math.max(1,asset.usefulLifeYears)))*(1-Math.min(0.95,asset.damagePercent/100));
 return <main className="dashboard-main section-page"><Link className="back-link" href="/assets"><ArrowLeft size={16}/> Back to assets</Link><section className="detail-hero"><div><span className={`status-pill ${asset.tone}`}><i/>{asset.status}</span><h1>{asset.name}</h1><p>{asset.id} · {asset.manufacturer} · {asset.model}</p></div><div className="heading-actions"><Link className="button primary" href={`/ai-assistant?asset=${encodeURIComponent(asset.id)}`}><BrainCircuit size={17}/> Diagnose with AI</Link><Link className="button secondary" href={`/work-orders?new=1&asset=${asset.id}`}><Wrench size={17}/> Create work order</Link><button className="button secondary" onClick={()=>setEditing(true)}><Pencil size={16}/> Edit asset</button></div></section>{error&&<p className="form-error">{error}</p>}
 <section className="detail-kpis"><article><span><small>Health</small><strong>{asset.health}%</strong></span></article><article><span><small>Purchase value</small><strong>QAR {asset.acquisitionCost.toLocaleString()}</strong></span></article><article><span><small>Current value</small><strong>QAR {current.toLocaleString(undefined,{maximumFractionDigits:0})}</strong></span></article><article><span><small>Warranty</small><strong>{asset.warrantyUntil||"Not recorded"}</strong></span></article></section>
 <section className="detail-section"><div className="section-title"><h2>Operational asset record</h2></div><dl className="asset-data-grid"><div><dt>Project</dt><dd>{asset.project}</dd></div><div><dt>Original PO</dt><dd>{asset.purchaseOrderId||"Not linked"}</dd></div><div><dt>Location</dt><dd><MapPin size={14}/>{asset.location}</dd></div><div><dt>Insurance</dt><dd>{asset.insured?"Insured":"Not insured"}</dd></div><div><dt>Condition adjustment</dt><dd>{asset.damagePercent}% damage · {asset.openBox?"Open box":"Sealed at purchase"}</dd></div><div><dt>Serial</dt><dd>{asset.serialNumber}</dd></div><div><dt>Useful life</dt><dd>{asset.usefulLifeYears} years</dd></div><div><dt>Description</dt><dd>{asset.notes||"No description recorded"}</dd></div></dl></section>
 <section className="detail-section"><div className="section-title"><div><h2>Asset History / Timeline</h2><p>Purchase, receiving, AI diagnosis and repair stay with this equipment record.</p></div></div><div className="asset-timeline">{timeline.map((item,index)=>{const Icon=iconFor(item.kind);return <article className="asset-timeline-item" key={item.key}><div className="asset-timeline-marker"><span><Icon size={17}/></span>{index<timeline.length-1&&<i/>}</div><div><time>{item.date?new Date(item.date).toLocaleString("en-QA",{dateStyle:"medium",timeStyle:item.date.includes("T")?"short":undefined}):"Date not recorded"}</time><h3>{item.title}</h3><p>{item.description}</p></div></article>})}{!timeline.length&&<p className="empty-row">No lifecycle events recorded yet.</p>}</div></section>
 {editing&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setEditing(false)}/><section className="modal-card activity-modal"><h2>Edit status and location</h2><form action={save}><label>Location<select name="location" defaultValue={asset.location}>{locations.map(l=><option key={l.name}>{l.name}</option>)}</select></label><label>Status<select name="status" defaultValue={asset.status}><option>Operational</option><option>Awaiting commissioning</option><option>Maintenance due</option><option>Out of service</option></select></label><label>Health %<input name="health" type="number" min="0" max="100" defaultValue={asset.health}/></label><label>Description<textarea name="notes" rows={4} defaultValue={asset.notes||""} placeholder="Equipment condition, usage note or important description"/></label><label>Warranty until<input name="warrantyUntil" type="date" defaultValue={asset.warrantyUntil}/></label><label className="check-filter"><input name="insured" type="checkbox" defaultChecked={asset.insured}/> Insured</label><button className="button primary full"><ShieldCheck size={16}/> Save asset update</button></form></section></div>}</main>
}
